name: Apply JSON2 to Chapters

on:
  workflow_dispatch:   # Manuell starten
  push:
    paths:
      - 'json2-*.json'   # startet automatisch, wenn du eine neue JSON2 hochlädst

jobs:
  apply-json2:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Dependencies installieren
        run: npm install js-yaml

      - name: JSON2 Script ausführen
        run: node scripts/apply-json2.js